repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args:
          - "--ignore=E501"
          - --fix
        files: ^custom_components/easybox_connect/\w*.py
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --quiet
        files: ^custom_components/easybox_connect/\w*.py
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^custom_components/easybox_connect/\w*.py
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^custom_components/easybox_connect/\w*.py
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.5.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # pre-commit run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py310-plus
          - --force
          - --keep-updates
        files: ^custom_components/easybox_connect/\w*.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
        files: ^custom_components/easybox_connect/\w*.py
      - id: check-json
        exclude: (.vscode|.devcontainer)
        files: ^custom_components/easybox_connect/\w*.py

